const my = {
  Home: "ပင်မစာမျက်နှာ",
  Products: "ကုန်ပစ္စည်းများ",
  Stock: "စတော့",
  Sales: "အရောင်း",
  Orders: "အရောင်း",
  Inventory: "စတော့",
  Suppliers: "ပေးသွင်းသူများ",
  "Price & Discount": "ဈေးနှုန်းနှင့် လျှော့ဈေး",
  "Price & Promotion": "ဈေးနှုန်းနှင့် ပရိုမိုးရှင်း",
  Payment: "ငွေပေးချေမှု",
  "Sale Report": "အရောင်းအစီရင်ခံစာ",
  "Product Report": "ကုန်ပစ္စည်းအစီရင်ခံစာ",
  Settings: "ဆက်တင်များ",
  Dashboard: "ပင်မစာမျက်နှာ",
  "Create Order": "အရောင်းအသစ်ဖန်တီးရန်",
  "Sale Records": "အရောင်းမှတ်တမ်းများ",
  Reports: "အစီရင်ခံစာများ",
  "Stock Details": "စတော့အသေးစိတ်",
  "Stock Movement": "စတော့အဝင်အထွက်",
  Note: "မှတ်စု",
  Logout: "ထွက်မည်",
  Business: "လုပ်ငန်း",
  "App Settings": "အက်ပ်ဆက်တင်များ",
  About: "အကြောင်းအရာ",
  "Shop Details": "ဆိုင်အချက်အလက်",
  Categories: "အမျိုးအစားများ",
  "Payment Method": "ငွေပေးချေမှုနည်းလမ်း",
  Premium: "ပရီမီယံ",
  "Backup & Restore": "အရန်သိမ်းနှင့် ပြန်လည်ရယူ",
  "Export Data": "ဒေတာထုတ်ယူရန်",
  "UI Language": "UI ဘာသာစကား",
  "Notification Settings": "အသိပေးချက်ဆက်တင်များ",
  "Biometric Lock": "လက်ဗွေလုံခြုံရေး",
  "Contact Support": "အကူအညီဆက်သွယ်ရန်",
  "Terms & Conditions": "စည်းကမ်းချက်များ",
  "Privacy Policy": "ကိုယ်ရေးအချက်အလက်မူဝါဒ",
  "App Version": "အက်ပ်ဗားရှင်း",
  English: "အင်္ဂလိပ်",
  Myanmar: "မြန်မာ",
  "Choose UI Language": "UI ဘာသာစကားရွေးပါ",
  "Edit Shop Details": "ဆိုင်အချက်အလက်ပြင်ရန်",
  "Shop Name": "ဆိုင်အမည်",
  Address: "လိပ်စာ",
  "Base Currency": "အခြေခံငွေကြေး",
  "Base currency is fixed when the shop is created.": "ဆိုင်ဖန်တီးချိန် သတ်မှတ်ထားသော အခြေခံငွေကြေးကို ပြောင်းလဲ၍မရပါ။",
  "Change Shop Logo": "ဆိုင်လိုဂိုပြောင်းရန်",
  "Choose Shop Logo": "ဆိုင်လိုဂိုရွေးရန်",
  "Enter shop name": "ဆိုင်အမည်ထည့်ပါ",
  "Enter shop address": "ဆိုင်လိပ်စာထည့်ပါ",
  "Shop details updated successfully.": "ဆိုင်အချက်အလက် ပြင်ဆင်ပြီးပါပြီ။",
  "Add Shop Logo": "ဆိုင်လိုဂိုထည့်ရန်",
  "Update Shop": "ဆိုင်အချက်အလက်ပြင်မည်",
  "Updating…": "ပြင်ဆင်နေသည်…",
  Cancel: "မလုပ်တော့ပါ",
  Close: "ပိတ်မည်",
  Save: "သိမ်းမည်",
  Edit: "ပြင်မည်",
  Delete: "ဖျက်မည်",
  Add: "ထည့်မည်",
  Active: "အသုံးပြုနေသည်",
  ON: "ဖွင့်",
  OFF: "ပိတ်",
  Notifications: "အသိပေးချက်များ",
  "No notifications": "အသိပေးချက်မရှိပါ",
  "Recently Added": "မကြာသေးမီက ထည့်ထားသည်",
  "Name (A-Z)": "အမည် (က-အ)",
  "Price (High to Low)": "ဈေးနှုန်း (အမြင့်မှအနိမ့်)",
  "Stock (Low to High)": "စတော့ (အနည်းမှအများ)",
  "Create an account to save": "သိမ်းဆည်းရန် အကောင့်ဖန်တီးပါ",
  "Guest mode lets you explore General POS. Create an account before saving stock, orders, payments, or other business records.": "ဧည့်သည်အဖြစ် General POS ကို လေ့လာနိုင်ပါသည်။ စတော့၊ အော်ဒါ၊ ငွေပေးချေမှုနှင့် လုပ်ငန်းမှတ်တမ်းများ မသိမ်းမီ အကောင့်ဖန်တီးပါ။",
  "Continue exploring": "ဆက်လက်လေ့လာမည်",
  "Create account": "အကောင့်ဖန်တီးမည်",
  Overview: "ခြုံငုံသုံးသပ်ချက်",
  "Top Seller": "အရောင်းအကောင်းဆုံး",
  "Slow Seller": "အရောင်းနှေး",
  "No Sale": "အရောင်းမရှိ",
  "Low Stock": "စတော့နည်း",
  "Out of Stock": "စတော့ကုန်",
  "Search products": "ကုန်ပစ္စည်းရှာရန်",
  "All categories": "အမျိုးအစားအားလုံး",
  "Total Products": "ကုန်ပစ္စည်းစုစုပေါင်း",
  "Total Quantity": "အရေအတွက်စုစုပေါင်း",
  "Low Stock Items": "စတော့နည်းပစ္စည်းများ",
  "Out of Stock Items": "စတော့ကုန်ပစ္စည်းများ",
  "Active Products": "အသုံးပြုနေသောပစ္စည်းများ",
  "In Stock": "စတော့ရှိ",
  "Need Attention": "ဂရုပြုရန်လို",
  "Currently Out": "လက်ရှိစတော့ကုန်",
  "Top Selling Products": "အရောင်းအကောင်းဆုံးပစ္စည်းများ",
  "Slow Selling Products": "အရောင်းနှေးသောပစ္စည်းများ",
  "No Sale Products": "အရောင်းမရှိသောပစ္စည်းများ",
  "Low Stock Products": "စတော့နည်းသောပစ္စည်းများ",
  "Out of Stock Products": "စတော့ကုန်သောပစ္စည်းများ",
  Product: "ကုန်ပစ္စည်း",
  "Qty Sold": "ရောင်းရသည့်အရေအတွက်",
  Revenue: "ရောင်းရငွေ",
  "Last Sold": "နောက်ဆုံးရောင်းသည့်ရက်",
  "Qty In Stock": "စတော့လက်ကျန်",
  Status: "အခြေအနေ",
  "Reorder Level": "ပြန်မှာရန်အဆင့်",
  "Cost Price": "အရင်းဈေး",
  "Selling Price": "ရောင်းဈေး",
  Margin: "အမြတ်ရာခိုင်နှုန်း",
  "Stock Value": "စတော့တန်ဖိုး",
  "Gross Profit": "စုစုပေါင်းအမြတ်",
  "View All": "အားလုံးကြည့်ရန်",
  "View all": "အားလုံးကြည့်ရန်",
  Filters: "စစ်ထုတ်ရန်",
  "DATE AND TIME": "ရက်စွဲနှင့်အချိန်",
  CATEGORY: "အမျိုးအစား",
  "Date and time": "ရက်စွဲနှင့်အချိန်",
  Reset: "ပြန်သတ်မှတ်",
  Apply: "အသုံးပြုမည်",
  From: "မှ",
  To: "အထိ",
  "30 days": "ရက် ၃၀",
  today: "ယနေ့",
  custom: "စိတ်ကြိုက်",
  "Inventory Summary by Status": "အခြေအနေအလိုက် စတော့အကျဉ်းချုပ်",
  Total: "စုစုပေါင်း",
  "No products in this category.": "ဤအမျိုးအစားတွင် ကုန်ပစ္စည်းမရှိပါ။",
  "No products match this report.": "ဤအစီရင်ခံစာနှင့် ကိုက်ညီသော ကုန်ပစ္စည်းမရှိပါ။",
  "Demand Status": "ဝယ်လိုအားအခြေအနေ",
  "Avg. Daily Sales": "တစ်ရက်ပျမ်းမျှအရောင်း",
  "Reorder Priority": "ပြန်မှာရန်ဦးစားပေး",
  "Out of Stock Since": "စတော့ကုန်နေသည့်ကာလ",
  "Suggested Reorder": "အကြံပြုပြန်မှာပမာဏ",
  "Urgent reorder": "အရေးပေါ်ပြန်မှာရန်",
  "Reorder soon": "မကြာမီပြန်မှာရန်",
  "Review first": "အရင်စစ်ဆေးရန်",
  "No sales": "အရောင်းမရှိ",
  "Do not reorder": "ပြန်မမှာပါနှင့်",
  "UI language could not be updated.": "UI ဘာသာစကားကို ပြင်ဆင်၍မရပါ။",
  "Review sales performance and product inventory insights.": "အရောင်းစွမ်းဆောင်ရည်နှင့် ကုန်ပစ္စည်းစတော့ အခြေအနေကို လေ့လာပါ။",
  "Review your store performance and inventory insights.": "ဆိုင်၏စွမ်းဆောင်ရည်နှင့် စတော့အခြေအနေကို လေ့လာပါ။",
  "Review sales, payments, order activity, and store performance.": "အရောင်း၊ ငွေပေးချေမှု၊ အော်ဒါနှင့် ဆိုင်စွမ်းဆောင်ရည်ကို လေ့လာပါ။",
  "Monitor product sales, slow-moving inventory, low stock, and out-of-stock items.": "ကုန်ပစ္စည်းအရောင်း၊ အရောင်းနှေးစတော့၊ စတော့နည်းနှင့် စတော့ကုန်ပစ္စည်းများကို စောင့်ကြည့်ပါ။",
  "Sales, payments, orders, cost, and profit insights.": "အရောင်း၊ ငွေပေးချေမှု၊ အော်ဒါ၊ အရင်းနှင့် အမြတ် အချက်အလက်များ။",
  "Product sales, low stock, and inventory movement insights.": "ကုန်ပစ္စည်းအရောင်း၊ စတော့နည်းနှင့် စတော့အဝင်အထွက် အချက်အလက်များ။",
  "Open report": "အစီရင်ခံစာဖွင့်မည်",
};

export const uiLanguageToLocale = (language) => language === "Myanmar" ? "my-MM" : "en-MM";
export const localeToUiLanguage = (locale) => locale === "my-MM" ? "Myanmar" : "English";
export const translateUi = (language, key) => language === "Myanmar" ? (my[key] ?? key) : key;
